# Generated by Django 4.2.25 on 2025-10-19 01:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_bodyweight', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutEnvironment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FitnessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=100, null=True)),
                ('pronouns', models.CharField(blank=True, choices=[('he/him', 'He/Him'), ('she/her', 'She/Her'), ('they/them', 'They/Them'), ('he/they', 'He/They'), ('she/they', 'She/They'), ('ze/hir', 'Ze/Hir'), ('prefer_not_to_say', 'Prefer not to say'), ('custom', 'Custom')], max_length=30, null=True)),
                ('custom_pronouns', models.CharField(blank=True, max_length=50, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('height_cm', models.FloatField(blank=True, null=True)),
                ('weight_kg', models.FloatField(blank=True, null=True)),
                ('body_fat_percentage', models.FloatField(blank=True, null=True)),
                ('goals', models.TextField(blank=True, null=True)),
                ('medical_conditions', models.TextField(blank=True, help_text='Any relevant medical conditions or injuries', null=True)),
                ('fitness_level', models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20, null=True)),
                ('exercise_frequency', models.IntegerField(blank=True, null=True)),
                ('fitness_goal', models.CharField(blank=True, choices=[('weight_loss', 'Weight Loss'), ('muscle_gain', 'Muscle Gain'), ('endurance', 'Endurance'), ('flexibility', 'Flexibility'), ('maintenance', 'Maintenance')], max_length=30, null=True)),
                ('target_weight_kg', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('available_equipment', models.ManyToManyField(blank=True, to='pace.equipment')),
                ('preferred_training_style', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pace.trainingstyle')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workout_location_preference', models.ManyToManyField(blank=True, to='pace.workoutenvironment')),
            ],
        ),
    ]
