# Generated by Django 4.2.25 on 2025-10-19 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pace', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutplan',
            name='exercises',
        ),
        migrations.AddField(
            model_name='exercise',
            name='workout_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='pace.workoutplan'),
        ),
    ]
