# Generated by Django 4.2.25 on 2025-10-19 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pace', '0002_remove_workoutplan_exercises_exercise_workout_plan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': ['order']},
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='exercise',
            unique_together={('workout_plan', 'order')},
        ),
    ]
