# Generated by Django 4.2.25 on 2025-10-19 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pace', '0002_fitnessprofile_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='MuscleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('difficulty_level', models.CharField(blank=True, choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10, null=True)),
                ('video_demo_url', models.URLField(blank=True, null=True)),
                ('Training_style', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pace.trainingstyle')),
                ('environment', models.ManyToManyField(blank=True, to='pace.workoutenvironment')),
                ('equipment', models.ManyToManyField(blank=True, to='pace.equipment')),
                ('muscle_group', models.ManyToManyField(blank=True, to='pace.musclegroup')),
            ],
        ),
    ]
