# Generated by Django 4.2.25 on 2025-10-19 03:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pace', '0004_workoutexercise_workoutplan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('rest_period_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pace.workoutplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseSetLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_number', models.PositiveIntegerField()),
                ('reps_completed', models.PositiveIntegerField(blank=True, null=True)),
                ('weight_kg', models.FloatField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pace.exercise')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pace.workoutsession')),
            ],
            options={
                'ordering': ['session', 'exercise', 'set_number'],
                'unique_together': {('session', 'exercise', 'set_number')},
            },
        ),
    ]
