# Generated by Django 4.2.25 on 2025-10-19 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pace', '0006_dailystreak'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='muscle_group',
            field=models.ManyToManyField(blank=True, to='pace.musclegroup'),
        ),
    ]
